#name: deploy-items
#
#on:
#  push:
#    branches:
#      - master
#    paths:
#      - 'items/**'
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - run: cd items && docker build -t fduran/items .
#      - run: docker login -u $DOCKER_USERNAME -p DOCKER_PASSWORD
#        env:
#          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
#          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
#      - run: docker push fduran/tickets
#      - uses: digitalocean/action-doctl@v2
#        with:
#          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
#      - run: doctl kubernetes cluster kubeconfig save orion-webapp
#      - run: kubectl rollout restart deployment items-depl
